### ISSUE TITLE
flood crosses boundaries

### ISSUE THREAD

**Issue by bristol-d** [binarymax/floodfill.js#14] opened 2017-06-13 13:27 UTC
I have the following image and I'm trying to fill the area around (170, 135).

![bristol](https://user-images.githubusercontent.com/21358450/27084417-c338e808-5043-11e7-8861-9c702483e50d.png)

    var canvas = document.getElementById("image");
    var dc = canvas.getContext('2d');
    var img = new Image();
    img.src = "Bristol.png";
    img.onload = function() {    
        dc.drawImage(img, 0, 0, canvas.width, canvas.height);
        dc.fillStyle = 'rgb(133, 153, 0)';
        dc.fillFlood(170, 135, 0);
    }

The flood escapes the area I'm trying to fill until it looks like this:

![download](https://user-images.githubusercontent.com/21358450/27084571-49c61490-5044-11e7-85d8-60054cd85668.png)

Is this a bug?

**Comment by MacroMan** [comment] 2017-06-13 13:55
I can also confirm this bug.

It's even worse with other areas of this image, for example, 220 x 135:
![screenshot from 2017-06-13 14-44-18](https://user-images.githubusercontent.com/1306658/27085752-1f3ab8c6-5048-11e7-9624-5e743c267ed9.png)

However issue does seem to be a duplicate of https://github.com/binarymax/floodfill.js/issues/10

**Comment by bristol-d** [comment] 2017-06-13 16:10
Ok, got it I think. In line 26:

    for(var j=w;j<e;j+=4) {

change to

    for(var j=w+4;j<e;j+=4) {

since e is the first differently coloured pixel to the right of the start, it makes sense to stop the loop before we hit it; similarly w is the first differently coloured pixel we hit to the left of the start so I think we need to begin the loop on the pixel *after* w.

My colouring of the wards of Bristol works fine with this change applied.

**Comment by arpeggiozz** [comment] 2017-07-25 16:04
@bristol-d Great job! I suppose it worth a PR.

**Closed as completed** 2017-09-20 17:14 UTC
